#aca se deben de poner las credenciales de supabse
spring.datasource.url=jdbc:postgresql://db.doobsnzkcyudkhdtinmv.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=IvOOnlmyNwYLmFzF

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Servidor
server.port=8080
#server.servlet.context-path=/api

# Nombre app
spring.application.name=cochiloco-backend

# Logs
logging.level.root=INFO
logging.level.com.cochiloco=DEBUG
